<?php
require "../PHPMailer/src/PHPMailer.php";
require '../PHPMailer/src/SMTP.php';
require '../PHPMailer/src/Exception.php';
use PHPMailer\PHPMailer\PHPMailer;

$name = $_POST["name"];
$email = $_POST["email"];
$subject = $_POST['subject'];
$message = $_POST['message'];
$body="<h3>Nouveau message de la part de : ".$name."</h3>
<p>Adresse mail : ".$email."</p>
<p>Sujet : ".$subject."</p>
<p>Message :".$message."</p>";


$mail = new PHPMailer();
$mail->isSMTP();
$mail->Host = 'mail.iraisemedia.com';
$mail->SMTPAuth = true;
$mail->Username = 'contact@iraisemedia.com'; //paste one generated by Mailtrap
$mail->Password = 'Contact.iraisemedia'; //paste one generated by Mailtrap
$mail->SMTPSecure = 'ssl';
$mail->Port = 465;
$mail->IsHTML(true);
$mail->From = "contact@iraisemedia.com";
$mail->FromName = "Service commercial";
$mail->Subject = "Nouveau message de la part de ".$name;
$mail->Body = $body;
$mail->AddAddress('contact@iraisemedia.com');
$mail->Send();